version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    command: --replSet rs0 --bind_ip_all --port 27017
#      - rs.initiate()

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379